export type BrandTier = "anchor" | "material-strong" | "aspirational" | "accessible";

export interface BrandProfile {
  slug: string;
  name: string;
  tier: BrandTier;
  intro: string;
  materialStrengths: string[];
  priceRange: string;
  naturalFiberEstimate: number;
  foundedYear?: number;
  headquarters?: string;
}

const TIER_LABELS: Record<BrandTier, string> = {
  anchor: "Anchor Brand",
  "material-strong": "Material-Strong",
  aspirational: "Aspirational Luxury",
  accessible: "Accessible Premium",
};

const TIER_DESCRIPTIONS: Record<BrandTier, string> = {
  anchor: "Established, high-trust brands with consistent material quality across collections.",
  "material-strong": "Brands that lead with natural fibers — linen, silk, wool, cashmere — and cleaner compositions.",
  aspirational: "Luxury houses with exceptional materials that set the standard for the industry.",
  accessible: "Quality-forward brands at approachable price points — strong conversion potential.",
};

export function getTierLabel(tier: BrandTier): string {
  return TIER_LABELS[tier];
}

export function getTierDescription(tier: BrandTier): string {
  return TIER_DESCRIPTIONS[tier];
}

export const BRAND_PROFILES: Record<string, BrandProfile> = {
  "khaite": {
    slug: "khaite",
    name: "Khaite",
    tier: "anchor",
    intro: "Founded in 2016 by Catherine Holstein, Khaite has rapidly become a defining voice in American luxury. The brand is known for its exacting approach to knitwear and tailoring, with cashmere and silk forming the backbone of most collections. INTERTEXE has verified 96 pieces — the cashmere and silk compositions are consistently exceptional.",
    materialStrengths: ["Cashmere", "Silk", "Wool", "Cotton"],
    priceRange: "$300 – $3,800",
    naturalFiberEstimate: 88,
    foundedYear: 2016,
    headquarters: "New York",
  },
  "anine-bing": {
    slug: "anine-bing",
    name: "Anine Bing",
    tier: "anchor",
    intro: "Anine Bing bridges Scandinavian minimalism with LA ease, offering wardrobe staples in silk, cashmere, cotton, and wool. The brand excels in knitwear and basics with strong natural fiber compositions. We've verified 113 pieces — the best-performing brand in our directory by volume of qualifying products.",
    materialStrengths: ["Cashmere", "Silk", "Cotton", "Wool"],
    priceRange: "$80 – $600",
    naturalFiberEstimate: 64,
    foundedYear: 2012,
    headquarters: "Los Angeles",
  },
  "vince": {
    slug: "vince",
    name: "Vince",
    tier: "anchor",
    intro: "Vince has built its reputation on effortless California luxury, with a focus on premium cashmere, silk, and cotton. The brand's strength lies in tactile, wearable pieces — sweaters, tees, and soft tailoring that prioritize material quality over trend. Consistently one of the most reliable brands for natural fibers at a contemporary price point.",
    materialStrengths: ["Cashmere", "Silk", "Cotton", "Wool"],
    priceRange: "$100 – $700",
    naturalFiberEstimate: 80,
    foundedYear: 2002,
    headquarters: "Los Angeles",
  },
  "rag-bone": {
    slug: "rag-bone",
    name: "Rag & Bone",
    tier: "anchor",
    intro: "Rag & Bone merges British tailoring heritage with downtown New York attitude. Known for premium denim and structured outerwear, the brand maintains strong cotton and wool compositions across its core lines. A reliable choice for well-constructed basics with genuine material substance.",
    materialStrengths: ["Cotton", "Denim", "Wool", "Leather"],
    priceRange: "$100 – $900",
    naturalFiberEstimate: 72,
    foundedYear: 2002,
    headquarters: "New York",
  },
  "frame": {
    slug: "frame",
    name: "Frame",
    tier: "anchor",
    intro: "Frame began as a denim brand and has evolved into a full lifestyle label rooted in LA-meets-Paris sensibility. The brand's denim remains its strongest offering, with high cotton content and minimal synthetic blends. Ready-to-wear extends into cashmere, silk, and linen — consistently above average in natural fiber content.",
    materialStrengths: ["Denim", "Cotton", "Cashmere", "Silk"],
    priceRange: "$150 – $800",
    naturalFiberEstimate: 74,
    foundedYear: 2012,
    headquarters: "Los Angeles",
  },
  "toteme": {
    slug: "toteme",
    name: "Totême",
    tier: "anchor",
    intro: "Stockholm-based Totême has become synonymous with refined Scandinavian minimalism. Every piece is designed with restraint and material integrity — wool coats, silk blouses, and cotton knits form the core of each collection. The brand consistently scores among the highest in our directory for natural fiber usage.",
    materialStrengths: ["Wool", "Silk", "Cotton", "Cashmere"],
    priceRange: "$200 – $1,500",
    naturalFiberEstimate: 92,
    foundedYear: 2014,
    headquarters: "Stockholm",
  },
  "theory": {
    slug: "theory",
    name: "Theory",
    tier: "anchor",
    intro: "Theory has defined modern workwear for over two decades, offering clean-lined tailoring in premium fabrications. The brand invests heavily in wool suiting, silk blouses, and cotton shirting. While some pieces incorporate performance blends, the core collection maintains strong natural fiber compositions.",
    materialStrengths: ["Wool", "Cotton", "Silk", "Linen"],
    priceRange: "$150 – $600",
    naturalFiberEstimate: 65,
    foundedYear: 1997,
    headquarters: "New York",
  },
  "sandro": {
    slug: "sandro",
    name: "Sandro",
    tier: "anchor",
    intro: "Sandro captures Parisian elegance at a contemporary price point. The brand's tops and knitwear often feature strong cotton and wool compositions, though dresses can lean more synthetic. Our verified data shows wide variation — shop selectively, focusing on knitwear and cotton-based pieces.",
    materialStrengths: ["Cotton", "Wool", "Linen"],
    priceRange: "$150 – $600",
    naturalFiberEstimate: 58,
    foundedYear: 1984,
    headquarters: "Paris",
  },
  "nanushka": {
    slug: "nanushka",
    name: "Nanushka",
    tier: "anchor",
    intro: "Budapest-born Nanushka blends Central European craftsmanship with modern, conscious design. The brand is known for its innovative use of vegan leather alternatives alongside strong linen, cotton, and silk pieces. A forward-thinking choice that doesn't sacrifice material quality for sustainability messaging.",
    materialStrengths: ["Linen", "Cotton", "Silk", "Vegan Leather"],
    priceRange: "$200 – $900",
    naturalFiberEstimate: 75,
    foundedYear: 2005,
    headquarters: "Budapest",
  },
  "max-mara": {
    slug: "max-mara",
    name: "Max Mara",
    tier: "anchor",
    intro: "Max Mara is an Italian institution, renowned for its iconic camel coat and impeccable wool tailoring. For over 70 years, the house has maintained unwavering standards in cashmere, wool, and camel hair. If you're investing in outerwear or tailored pieces, few brands match this level of material consistency.",
    materialStrengths: ["Wool", "Cashmere", "Camel Hair", "Cotton"],
    priceRange: "$400 – $4,000",
    naturalFiberEstimate: 70,
    foundedYear: 1951,
    headquarters: "Reggio Emilia, Italy",
  },
  "the-kooples": {
    slug: "the-kooples",
    name: "The Kooples",
    tier: "anchor",
    intro: "The Kooples brings Parisian rock-chic energy to contemporary fashion, with a focus on silk blouses, leather jackets, and wool suiting. The brand's silk and wool pieces perform well in our quality analysis, though synthetics appear in some casualwear lines. Best for statement pieces with genuine material quality.",
    materialStrengths: ["Silk", "Wool", "Leather", "Cotton"],
    priceRange: "$150 – $800",
    naturalFiberEstimate: 60,
    foundedYear: 2008,
    headquarters: "Paris",
  },

  "eileen-fisher": {
    slug: "eileen-fisher",
    name: "Eileen Fisher",
    tier: "material-strong",
    intro: "Eileen Fisher is a pioneer in responsible fashion, building entire collections around organic cotton, linen, silk, and wool. The brand's commitment to natural fibers is among the strongest in the industry — nearly every piece meets or exceeds our quality threshold. A cornerstone brand for the fabric-conscious shopper.",
    materialStrengths: ["Organic Cotton", "Linen", "Silk", "Wool"],
    priceRange: "$100 – $500",
    naturalFiberEstimate: 90,
    foundedYear: 1984,
    headquarters: "New York",
  },
  "a-p-c-": {
    slug: "a-p-c-",
    name: "A.P.C.",
    tier: "material-strong",
    intro: "A.P.C. is the gold standard for premium denim and understated Parisian style. Founded by Jean Touitou, the brand builds its identity on raw selvedge denim, cotton shirting, and wool outerwear. Material integrity is central to the brand's philosophy — synthetics are the exception, never the rule.",
    materialStrengths: ["Denim", "Cotton", "Wool", "Leather"],
    priceRange: "$100 – $600",
    naturalFiberEstimate: 79,
    foundedYear: 1987,
    headquarters: "Paris",
  },
  "cos": {
    slug: "cos",
    name: "COS",
    tier: "material-strong",
    intro: "COS occupies a unique space — offering architectural, minimalist design at accessible prices with surprisingly strong natural fiber content. The brand's wool, cotton, and silk pieces regularly outperform competitors at similar price points. Shop selectively: the best COS pieces rival brands at twice the price.",
    materialStrengths: ["Wool", "Cotton", "Silk", "Linen"],
    priceRange: "$50 – $300",
    naturalFiberEstimate: 55,
    foundedYear: 2007,
    headquarters: "London",
  },
  "arket": {
    slug: "arket",
    name: "Arket",
    tier: "material-strong",
    intro: "Arket takes a transparency-first approach to modern essentials, listing full material compositions and sourcing origins. The brand's linen, organic cotton, and wool basics consistently deliver above-average natural fiber content. One of the best value propositions for quality-conscious shoppers on a budget.",
    materialStrengths: ["Linen", "Organic Cotton", "Wool", "Alpaca"],
    priceRange: "$30 – $250",
    naturalFiberEstimate: 68,
    foundedYear: 2017,
    headquarters: "Stockholm",
  },
  "equipment": {
    slug: "equipment",
    name: "Equipment",
    tier: "material-strong",
    intro: "Equipment is synonymous with the perfect silk shirt. For decades, the brand has built its reputation on pure silk fabrications — blouses, dresses, and camisoles in washed silk that improves with wear. If silk is your fabric of choice, this is the definitive destination.",
    materialStrengths: ["Silk", "Cashmere", "Cotton"],
    priceRange: "$150 – $500",
    naturalFiberEstimate: 82,
    foundedYear: 1976,
    headquarters: "Los Angeles",
  },
  "nili-lotan": {
    slug: "nili-lotan",
    name: "Nili Lotan",
    tier: "material-strong",
    intro: "Nili Lotan embodies refined ease — every piece is designed to feel effortless while being constructed from premium natural materials. The brand excels in cashmere, silk, and cotton, with a particular strength in knitwear and tailored separates. A designer's designer, trusted by stylists for reliable quality.",
    materialStrengths: ["Cashmere", "Silk", "Cotton", "Wool"],
    priceRange: "$200 – $1,200",
    naturalFiberEstimate: 82,
    foundedYear: 2003,
    headquarters: "New York",
  },
  "filippa-k": {
    slug: "filippa-k",
    name: "Filippa K",
    tier: "material-strong",
    intro: "Filippa K represents the best of Scandinavian design philosophy — timeless, minimal, and material-first. The brand prioritizes organic cotton, recycled wool, and silk in collections designed to last multiple seasons. A strong choice for building a wardrobe of natural fiber essentials.",
    materialStrengths: ["Organic Cotton", "Wool", "Silk", "Linen"],
    priceRange: "$100 – $600",
    naturalFiberEstimate: 78,
    foundedYear: 1993,
    headquarters: "Stockholm",
  },
  "joseph": {
    slug: "joseph",
    name: "Joseph",
    tier: "material-strong",
    intro: "Joseph has been a London staple for tailored essentials since the 1960s. The brand is known for precision-cut trousers, cashmere knitwear, and silk blouses — all built on a foundation of exceptional natural materials. Consistently one of the highest-scoring brands in our directory.",
    materialStrengths: ["Cashmere", "Silk", "Wool", "Cotton"],
    priceRange: "$200 – $1,000",
    naturalFiberEstimate: 90,
    foundedYear: 1966,
    headquarters: "London",
  },
  "margaret-howell": {
    slug: "margaret-howell",
    name: "Margaret Howell",
    tier: "material-strong",
    intro: "Margaret Howell represents the pinnacle of British understated design. Every collection is built around heritage fabrics — Irish linen, Scottish wool, Japanese cotton. The brand sources from the world's finest mills and maintains near-perfect natural fiber compositions. A quiet masterclass in material quality.",
    materialStrengths: ["Linen", "Wool", "Cotton", "Silk"],
    priceRange: "$200 – $1,200",
    naturalFiberEstimate: 95,
    foundedYear: 1970,
    headquarters: "London",
  },
  "citizens-of-humanity": {
    slug: "citizens-of-humanity",
    name: "Citizens of Humanity",
    tier: "material-strong",
    intro: "Citizens of Humanity elevates denim to an art form, using premium cotton and minimal stretch blends. The brand's commitment to responsible manufacturing extends to its material choices — organic cotton and natural indigo dyes feature prominently. For denim purists who care about what's in their jeans.",
    materialStrengths: ["Cotton", "Denim", "Organic Cotton"],
    priceRange: "$200 – $400",
    naturalFiberEstimate: 78,
    foundedYear: 2003,
    headquarters: "Los Angeles",
  },
  "agolde": {
    slug: "agolde",
    name: "AGOLDE",
    tier: "material-strong",
    intro: "AGOLDE has redefined modern denim with vintage-inspired washes and high cotton content. The brand maintains strong organic cotton compositions and minimal synthetic blending across its core denim line. A go-to for fashion-forward denim with genuine material substance.",
    materialStrengths: ["Organic Cotton", "Denim", "Cotton"],
    priceRange: "$150 – $350",
    naturalFiberEstimate: 76,
    foundedYear: 2014,
    headquarters: "Los Angeles",
  },
  "ami-paris": {
    slug: "ami-paris",
    name: "Ami Paris",
    tier: "material-strong",
    intro: "Ami Paris captures the spirit of relaxed Parisian menswear with a strong emphasis on wool, cotton, and cashmere. Founded by Alexandre Mattiussi, the brand offers accessible luxury with consistently natural compositions. Knitwear and outerwear are particular strengths.",
    materialStrengths: ["Wool", "Cotton", "Cashmere"],
    priceRange: "$150 – $800",
    naturalFiberEstimate: 75,
    foundedYear: 2011,
    headquarters: "Paris",
  },

  "the-row": {
    slug: "the-row",
    name: "The Row",
    tier: "aspirational",
    intro: "The Row defines the apex of quiet luxury. Founded by Mary-Kate and Ashley Olsen, every garment is constructed from the world's finest materials — Italian cashmere, Japanese cotton, French silk. The brand's obsessive attention to material quality makes it the gold standard in our directory.",
    materialStrengths: ["Cashmere", "Silk", "Wool", "Cotton"],
    priceRange: "$500 – $8,000",
    naturalFiberEstimate: 96,
    foundedYear: 2006,
    headquarters: "New York",
  },
  "brunello-cucinelli": {
    slug: "brunello-cucinelli",
    name: "Brunello Cucinelli",
    tier: "aspirational",
    intro: "Brunello Cucinelli is the undisputed king of cashmere. Based in Solomeo, Umbria, the brand sources the world's finest cashmere, silk, and wool, transforming them into garments of extraordinary softness and longevity. If material quality is your north star, Cucinelli sets the standard.",
    materialStrengths: ["Cashmere", "Silk", "Wool", "Linen"],
    priceRange: "$800 – $12,000",
    naturalFiberEstimate: 97,
    foundedYear: 1978,
    headquarters: "Solomeo, Italy",
  },
  "loro-piana": {
    slug: "loro-piana",
    name: "Loro Piana",
    tier: "aspirational",
    intro: "Loro Piana doesn't just use the finest fibers — it owns the supply chain. From Mongolian cashmere to New Zealand merino to Peruvian vicuña, the house controls material quality from farm to garment. The highest-scoring brand in our entire directory. Simply unmatched.",
    materialStrengths: ["Cashmere", "Vicuña", "Wool", "Silk", "Linen"],
    priceRange: "$500 – $20,000",
    naturalFiberEstimate: 98,
    foundedYear: 1924,
    headquarters: "Quarona, Italy",
  },
  "jil-sander": {
    slug: "jil-sander",
    name: "Jil Sander",
    tier: "aspirational",
    intro: "Jil Sander pioneered minimalist luxury — where the material is the design. Under creative director Lucie and Luke Meier, the house continues to prioritize the world's finest wools, silks, and cottons. Clean lines demand perfect fabric, and Jil Sander delivers.",
    materialStrengths: ["Wool", "Silk", "Cotton", "Cashmere"],
    priceRange: "$400 – $5,000",
    naturalFiberEstimate: 91,
    foundedYear: 1968,
    headquarters: "Milan",
  },
  "lemaire": {
    slug: "lemaire",
    name: "Lemaire",
    tier: "aspirational",
    intro: "Lemaire creates clothing of quiet intelligence — each piece balances structure with softness through masterful material selection. Japanese cottons, Italian wools, and French linens are hallmarks of the brand. Christophe Lemaire's dedication to fabric makes every garment a study in material excellence.",
    materialStrengths: ["Cotton", "Wool", "Linen", "Silk"],
    priceRange: "$300 – $2,000",
    naturalFiberEstimate: 93,
    foundedYear: 1992,
    headquarters: "Paris",
  },
  "bottega-veneta": {
    slug: "bottega-veneta",
    name: "Bottega Veneta",
    tier: "aspirational",
    intro: "Bottega Veneta is built on the principle that craft speaks louder than logos. While famous for its intrecciato leather, the house also excels in cashmere knits, wool tailoring, and cotton jersey. Material quality is embedded in the brand's DNA — synthetics are rare and reserved for technical pieces.",
    materialStrengths: ["Leather", "Cashmere", "Wool", "Cotton"],
    priceRange: "$500 – $10,000",
    naturalFiberEstimate: 82,
    foundedYear: 1966,
    headquarters: "Vicenza, Italy",
  },
  "chloe": {
    slug: "chloe",
    name: "Chloé",
    tier: "aspirational",
    intro: "Chloé is the house of romantic femininity, built on a legacy of silk, lace, and fine cotton. Under Chemena Kamali, the brand continues to prioritize natural materials — flowing silk dresses, wool coats, and cotton blouses form the collection's backbone. A consistently strong performer in our natural fiber analysis.",
    materialStrengths: ["Silk", "Cotton", "Wool", "Lace"],
    priceRange: "$400 – $4,000",
    naturalFiberEstimate: 83,
    foundedYear: 1952,
    headquarters: "Paris",
  },
  "loewe": {
    slug: "loewe",
    name: "Loewe",
    tier: "aspirational",
    intro: "Under Jonathan Anderson, Loewe has become a material playground — merging artisanal craft with fashion innovation. The brand's leather goods are legendary, and ready-to-wear features premium wool, silk, and cotton. A house where material experimentation meets genuine quality.",
    materialStrengths: ["Leather", "Wool", "Silk", "Cotton", "Linen"],
    priceRange: "$500 – $8,000",
    naturalFiberEstimate: 85,
    foundedYear: 1846,
    headquarters: "Madrid",
  },
  "stella-mccartney": {
    slug: "stella-mccartney",
    name: "Stella McCartney",
    tier: "aspirational",
    intro: "Stella McCartney has proven that luxury and sustainability can coexist. The brand avoids leather and fur entirely, instead investing in premium organic cotton, recycled wool, and innovative plant-based materials. A trailblazer for conscious luxury with strong natural fiber compositions.",
    materialStrengths: ["Organic Cotton", "Wool", "Silk", "Viscose"],
    priceRange: "$300 – $3,000",
    naturalFiberEstimate: 80,
    foundedYear: 2001,
    headquarters: "London",
  },
  "acne-studios": {
    slug: "acne-studios",
    name: "Acne Studios",
    tier: "aspirational",
    intro: "Acne Studios merges Scandinavian minimalism with creative edge, using premium wool, leather, and denim to create pieces that balance art and wearability. The brand's wool outerwear and denim lines are particularly strong in natural fiber content. A consistent performer for the design-minded shopper.",
    materialStrengths: ["Wool", "Denim", "Cotton", "Leather"],
    priceRange: "$200 – $2,500",
    naturalFiberEstimate: 78,
    foundedYear: 1996,
    headquarters: "Stockholm",
  },

  "reformation": {
    slug: "reformation",
    name: "Reformation",
    tier: "accessible",
    intro: "Reformation has made sustainable fashion desirable, offering trend-driven pieces in linen, organic cotton, and Tencel. The brand is transparent about its environmental impact and maintains strong natural fiber compositions, particularly in its linen and cotton lines. Our verified data shows 87% of pieces meet our threshold.",
    materialStrengths: ["Linen", "Organic Cotton", "Tencel", "Silk"],
    priceRange: "$80 – $400",
    naturalFiberEstimate: 66,
    foundedYear: 2009,
    headquarters: "Los Angeles",
  },
  "everlane": {
    slug: "everlane",
    name: "Everlane",
    tier: "accessible",
    intro: "Everlane built its brand on radical transparency — publishing factory details, cost breakdowns, and material sources. The brand's cotton tees, wool sweaters, and cashmere knits offer genuine quality at fair prices. Best in class for the value-conscious buyer who refuses to compromise on material substance.",
    materialStrengths: ["Cotton", "Cashmere", "Wool", "Linen"],
    priceRange: "$30 – $250",
    naturalFiberEstimate: 70,
    foundedYear: 2010,
    headquarters: "San Francisco",
  },
  "other-stories": {
    slug: "other-stories",
    name: "& Other Stories",
    tier: "accessible",
    intro: "& Other Stories offers design-led fashion with a surprisingly strong material profile for its price point. The brand features dedicated collections in silk, wool, and linen, alongside its core cotton range. Shop selectively — the natural fiber pieces punch well above their weight.",
    materialStrengths: ["Cotton", "Silk", "Wool", "Linen"],
    priceRange: "$40 – $250",
    naturalFiberEstimate: 60,
    foundedYear: 2013,
    headquarters: "Stockholm",
  },
  "massimo-dutti": {
    slug: "massimo-dutti",
    name: "Massimo Dutti",
    tier: "accessible",
    intro: "Massimo Dutti delivers polished European style with material quality that regularly surprises. The brand's wool suiting, linen shirting, and cotton basics compete with brands at double the price. One of the strongest accessible options for building a natural-fiber wardrobe.",
    materialStrengths: ["Wool", "Linen", "Cotton", "Cashmere"],
    priceRange: "$50 – $400",
    naturalFiberEstimate: 65,
    foundedYear: 1985,
    headquarters: "Barcelona",
  },
  "re-done": {
    slug: "re-done",
    name: "Re/Done",
    tier: "accessible",
    intro: "Re/Done pioneered the vintage-repurposed denim movement, transforming authentic Levi's into modern fits. The brand has expanded into cotton tees and basics, all built on a foundation of genuine material quality and circularity. For denim lovers who appreciate both the craft and the history in their jeans.",
    materialStrengths: ["Denim", "Cotton", "Vintage Cotton"],
    priceRange: "$100 – $400",
    naturalFiberEstimate: 73,
    foundedYear: 2014,
    headquarters: "Los Angeles",
  },
  "quince": {
    slug: "quince",
    name: "Quince",
    tier: "accessible",
    intro: "Quince operates on a direct-from-factory model, offering Mongolian cashmere, organic cotton, and European linen at a fraction of traditional retail prices. The brand's cashmere sweaters and linen pieces offer remarkable quality for the price. The strongest value proposition in our directory.",
    materialStrengths: ["Cashmere", "Linen", "Organic Cotton", "Silk"],
    priceRange: "$20 – $150",
    naturalFiberEstimate: 80,
    foundedYear: 2018,
    headquarters: "San Francisco",
  },
};

export function getBrandProfile(slug: string): BrandProfile | null {
  return BRAND_PROFILES[slug] || null;
}

export function getBrandProfileByName(name: string): BrandProfile | null {
  const lower = name.toLowerCase().trim();
  for (const profile of Object.values(BRAND_PROFILES)) {
    if (profile.name.toLowerCase() === lower) return profile;
  }
  return null;
}

export function getAllProfiles(): BrandProfile[] {
  return Object.values(BRAND_PROFILES);
}

export function getProfilesByTier(tier: BrandTier): BrandProfile[] {
  return Object.values(BRAND_PROFILES).filter(p => p.tier === tier);
}
