const KNOWN_DOMAINS: Record<string, string> = {
  "alexander wang": "alexanderwang.com",
  "ralph lauren": "ralphlauren.com",
  "tommy hilfiger": "tommyhilfiger.com",
  "calvin klein": "calvinklein.com",
  "michael kors": "michaelkors.com",
  "marc jacobs": "marcjacobs.com",
  "kate spade": "katespade.com",
  "tory burch": "toryburch.com",
  "diane von furstenberg": "dvf.com",
  "oscar de la renta": "oscardelarenta.com",
  "carolina herrera": "carolinaherrera.com",
  "helmut lang": "helmutlang.com",
  "rag & bone": "rag-bone.com",
  "acne studios": "acnestudios.com",
  "a.p.c.": "apc.fr",
  "maison margiela": "maisonmargiela.com",
  "comme des garçons": "comme-des-garcons.com",
  "rick owens": "rickowens.eu",
  "ann demeulemeester": "anndemeulemeester.com",
  "dries van noten": "driesvannoten.com",
  "the row": "therow.com",
  "bottega veneta": "bottegaveneta.com",
  "saint laurent": "ysl.com",
  "louis vuitton": "louisvuitton.com",
  "gucci": "gucci.com",
  "prada": "prada.com",
  "burberry": "burberry.com",
  "givenchy": "givenchy.com",
  "balenciaga": "balenciaga.com",
  "valentino": "valentino.com",
  "fendi": "fendi.com",
  "dior": "dior.com",
  "celine": "celine.com",
  "loewe": "loewe.com",
  "chanel": "chanel.com",
  "hermès": "hermes.com",
  "versace": "versace.com",
  "dolce & gabbana": "dolcegabbana.com",
  "armani": "armani.com",
  "giorgio armani": "armani.com",
  "emporio armani": "armani.com",
  "moncler": "moncler.com",
  "stone island": "stoneisland.com",
  "off-white": "off---white.com",
  "fear of god": "fearofgod.com",
  "amiri": "amiri.com",
  "tom ford": "tomford.com",
  "stella mccartney": "stellamccartney.com",
  "isabel marant": "isabelmarant.com",
  "nanushka": "nanushka.com",
  "ganni": "ganni.com",
  "cos": "cos.com",
  "arket": "arket.com",
  "& other stories": "stories.com",
  "zara": "zara.com",
  "massimo dutti": "massimodutti.com",
  "uniqlo": "uniqlo.com",
  "j.crew": "jcrew.com",
  "club monaco": "clubmonaco.com",
  "theory": "theory.com",
  "vince": "vince.com",
  "equipment": "equipmentfr.com",
  "frame": "frame-store.com",
  "ag jeans": "agjeans.com",
  "citizens of humanity": "citizensofhumanity.com",
  "brunello cucinelli": "brunellocucinelli.com",
  "loro piana": "loropiana.com",
  "ermenegildo zegna": "zegna.com",
  "zegna": "zegna.com",
  "tod's": "tods.com",
  "salvatore ferragamo": "ferragamo.com",
  "bally": "bally.com",
  "church's": "church-footwear.com",
  "jimmy choo": "jimmychoo.com",
  "manolo blahnik": "manoloblahnik.com",
  "christian louboutin": "christianlouboutin.com",
  "nike": "nike.com",
  "adidas": "adidas.com",
  "new balance": "newbalance.com",
  "converse": "converse.com",
  "vans": "vans.com",
  "dr. martens": "drmartens.com",
  "birkenstock": "birkenstock.com",
  "ugg": "ugg.com",
  "north face": "thenorthface.com",
  "the north face": "thenorthface.com",
  "patagonia": "patagonia.com",
  "arc'teryx": "arcteryx.com",
  "canada goose": "canadagoose.com",
  "barbour": "barbour.com",
  "woolrich": "woolrich.com",
  "allsaints": "allsaints.com",
  "ted baker": "tedbaker.com",
  "paul smith": "paulsmith.com",
  "vivienne westwood": "viviennewestwood.com",
  "alexander mcqueen": "alexandermcqueen.com",
  "etro": "etro.com",
  "missoni": "missoni.com",
  "max mara": "maxmara.com",
  "weekend max mara": "weekendmaxmara.com",
  "sportmax": "sportmax.com",
  "jil sander": "jilsander.com",
  "mm6 maison margiela": "maisonmargiela.com",
  "marni": "marni.com",
  "sacai": "sacai.jp",
  "issey miyake": "isseymiyake.com",
  "kenzo": "kenzo.com",
  "ami paris": "amiparis.com",
  "jacquemus": "jacquemus.com",
  "lemaire": "lemaire.fr",
  "auralee": "auralee.jp",
  "our legacy": "ourlegacy.com",
  "stüssy": "stussy.com",
  "stussy": "stussy.com",
  "palace": "palaceskateboards.com",
  "carhartt wip": "carhartt-wip.com",
  "a bathing ape": "bape.com",
  "human made": "humanmade.jp",
  "undercover": "undercoverism.com",
  "neighborhood": "neighborhood.jp",
  "wtaps": "wtaps.com",
  "visvim": "visvim.tv",
  "kapital": "kapital.jp",
  "needles": "needles.jp",
  "margaret howell": "margarethowell.co.uk",
  "sunspel": "sunspel.com",
  "john smedley": "johnsmedley.com",
  "orlebar brown": "orlebarbrown.com",
  "reiss": "reiss.com",
  "sandro": "sandro-paris.com",
  "maje": "maje.com",
  "claudie pierlot": "claudiepierlot.com",
  "zadig & voltaire": "zadig-et-voltaire.com",
  "iro": "iroparis.com",
  "ba&sh": "ba-sh.com",
  "sézane": "sezane.com",
  "reformation": "thereformation.com",
  "totême": "toteme-studio.com",
  "anine bing": "aninebing.com",
  "agolde": "agolde.com",
  "khaite": "khaite.com",
  "proenza schouler": "proenzaschouler.com",
  "3.1 phillip lim": "31philliplim.com",
  "coach": "coach.com",
  "longchamp": "longchamp.com",
  "mulberry": "mulberry.com",
  "furla": "furla.com",
  "mcm": "mcmworldwide.com",
  "goyard": "goyard.com",
  "moynat": "moynat.com",
  "rimowa": "rimowa.com",
  "tumi": "tumi.com",
  "hugo boss": "hugoboss.com",
  "boss": "hugoboss.com",
  "diesel": "diesel.com",
  "dsquared2": "dsquared2.com",
  "moschino": "moschino.com",
  "just cavalli": "justcavalli.com",
  "philipp plein": "plein.com",
  "balmain": "balmain.com",
  "lanvin": "lanvin.com",
  "rochas": "rochas.com",
  "mugler": "mugler.com",
  "jean paul gaultier": "jeanpaulgaultier.com",
  "courrèges": "courreges.com",
  "rabanne": "rabanne.com",
  "chloé": "chloe.com",
  "see by chloé": "seebychloe.com",
};

function guessDomain(brandName: string): string | null {
  const lower = brandName.toLowerCase().trim();
  if (KNOWN_DOMAINS[lower]) return KNOWN_DOMAINS[lower];

  const cleaned = lower
    .replace(/[®™*#°]/g, '')
    .replace(/\s+/g, '')
    .replace(/[&+]/g, '')
    .replace(/[''`]/g, '')
    .replace(/[^a-z0-9.-]/g, '');

  if (cleaned.length < 2) return null;
  return `${cleaned}.com`;
}

export function getBrandScreenshotUrl(brandName: string, width = 600): string | null {
  const domain = guessDomain(brandName);
  if (!domain) return null;
  return `https://image.thum.io/get/width/${width}/https://${domain}`;
}

export function getBrandLogoUrl(brandName: string): string | null {
  const domain = guessDomain(brandName);
  if (!domain) return null;
  return `https://t2.gstatic.com/faviconV2?client=SOCIAL&type=FAVICON&fallback_opts=TYPE,SIZE,URL&url=https://${domain}&size=128`;
}

export { guessDomain };
