export const CURATED_QUALITY_SCORES: Record<string, number> = {
  "the row": 96,
  "brunello cucinelli": 97,
  "loro piana": 98,
  "margaret howell": 95,
  "lemaire": 93,
  "jil sander": 91,
  "totême": 92,
  "toteme": 92,
  "eileen fisher": 90,
  "joseph": 90,

  "khaite": 88,
  "loewe": 85,
  "bottega veneta": 82,
  "chloé": 83,
  "chloe": 83,
  "stella mccartney": 80,
  "acne studios": 78,
  "isabel marant": 76,
  "nanushka": 75,
  "proenza schouler": 77,
  "frame": 74,
  "equipment": 82,
  "citizens of humanity": 78,
  "agolde": 76,
  "rag & bone": 72,
  "re/done": 73,
  "vince": 80,
  "ami paris": 75,
  "a.p.c.": 79,
  "nili lotan": 82,
  "filippa k": 78,

  "sézane": 68,
  "sezane": 68,
  "ba&sh": 62,
  "ganni": 65,
  "anine bing": 64,
  "reformation": 66,
  "sandro": 58,
  "maje": 55,
  "reiss": 60,
  "theory": 65,
  "club monaco": 58,
  "iro": 56,
  "zadig & voltaire": 54,
  "arket": 68,
  "& other stories": 60,
  "claudie pierlot": 52,

  "the kooples": 60,
  "allsaints": 48,
  "all saints": 48,
  "ted baker": 42,
  "cos": 55,
  "max mara": 70,
  "zimmermann": 62,
  "jacquemus": 72,

  "everlane": 70,
  "quince": 80,
  "massimo dutti": 65,
  "l'agence": 62,
  "lagence": 62,

  "loulou studio": 78,
  "st. agni": 76,
  "maria mcmanus": 82,
};

export function getCuratedScore(brandName: string): number | null {
  const lower = (brandName || "").toLowerCase().trim();
  return CURATED_QUALITY_SCORES[lower] ?? null;
}
