-- INTERTEXE Products Table for Supabase
-- Run this in your Supabase SQL Editor (https://supabase.com/dashboard → SQL Editor)

CREATE TABLE IF NOT EXISTS products (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  brand_slug TEXT NOT NULL,
  brand_name TEXT NOT NULL,
  name TEXT NOT NULL,
  product_id TEXT NOT NULL UNIQUE,
  url TEXT NOT NULL,
  image_url TEXT,
  price TEXT,
  composition TEXT,
  natural_fiber_percent INTEGER,
  category TEXT NOT NULL DEFAULT 'dresses',
  approved TEXT NOT NULL DEFAULT 'yes',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Enable Row Level Security (optional, recommended)
ALTER TABLE products ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public read" ON products FOR SELECT USING (true);

-- ============================
-- Insert 48 verified products
-- ============================
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('reformation', 'Reformation', 'Ailany Dress', '1319572JGR', 'https://www.thereformation.com/products/ailany-dress/1319572JGR.html', 'https://media.thereformation.com/image/upload/f_auto,q_auto,dpr_1.0/w_800,c_scale//PRD-SFCC/1319572/JADE_GREEN/1319572.1.JADE_GREEN?_s=RAABAB0', '$248.00', '100% Viscose (wood pulp)', 100, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('reformation', 'Reformation', 'Anaiis Silk Dress', '1314547TAV', 'https://www.thereformation.com/products/anaiis-silk-dress/1314547TAV.html', 'https://media.thereformation.com/image/upload/f_auto,q_auto,dpr_1.0/w_800,c_scale//PRD-SFCC/1314547/TARRAGON/1314547.1.TARRAGON?_s=RAABAB0', '$398.00', '100% Silk', 100, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('reformation', 'Reformation', 'Birdie Linen Dress', '1320101OVI', 'https://www.thereformation.com/products/birdie-linen-dress/1320101OVI.html', 'https://media.thereformation.com/image/upload/f_auto,q_auto,dpr_1.0/w_800,c_scale//PRD-SFCC/1320101/LOVIE/1320101.1.LOVIE?_s=RAABAB0', '$298.00', '100% Linen', 100, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('reformation', 'Reformation', 'Cecilia Linen Dress', '1319452DEK', 'https://www.thereformation.com/products/cecilia-linen-dress/1319452DEK.html', 'https://media.thereformation.com/image/upload/f_auto,q_auto,dpr_1.0/w_800,c_scale//PRD-SFCC/1319452/DARK_OATMEAL/1319452.1.DARK_OATMEAL?_s=RAABAB0', '$278.00', '100% Linen', 100, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('reformation', 'Reformation', 'Claribel Dress', '1319500CRM', 'https://www.thereformation.com/products/claribel-dress/1319500CRM.html', 'https://media.thereformation.com/image/upload/f_auto,q_auto,dpr_1.0/w_800,c_scale//PRD-SFCC/1319500/CREAM/1319500.1.CREAM?_s=RAABAB0', '$248.00', '100% Viscose (wood pulp)', 100, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('reformation', 'Reformation', 'Doranni Dress', '1319657JGR', 'https://www.thereformation.com/products/doranni-dress/1319657JGR.html', 'https://media.thereformation.com/image/upload/f_auto,q_auto,dpr_1.0/w_800,c_scale//PRD-SFCC/1319657/JADE_GREEN/1319657.1.JADE_GREEN?_s=RAABAB0', '$298.00', '100% Viscose (wood pulp)', 100, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('reformation', 'Reformation', 'Eden Silk Dress', '1319612PPO', 'https://www.thereformation.com/products/eden-silk-dress/1319612PPO.html', 'https://media.thereformation.com/image/upload/f_auto,q_auto,dpr_1.0/w_800,c_scale//PRD-SFCC/1319612/PLUTO_DOT/1319612.1.PLUTO_DOT?_s=RAABAB0', '$248.00', '100% Silk', 100, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('reformation', 'Reformation', 'Frankie Silk Dress', '1304134RCM', 'https://www.thereformation.com/products/frankie-silk-dress/1304134RCM.html', 'https://media.thereformation.com/image/upload/f_auto,q_auto,dpr_1.0/w_800,c_scale//PRD-SFCC/1304134/MERCY/1304134.1.MERCY?_s=RAABAB0', '$298.00', '100% Silk', 100, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('reformation', 'Reformation', 'Janu Linen Mini Dress', '1319548LPS', 'https://www.thereformation.com/products/janu-linen-mini-dress/1319548LPS.html', 'https://media.thereformation.com/image/upload/f_auto,q_auto,dpr_1.0/w_800,c_scale//PRD-SFCC/1319548/LIPSTICK/1319548.1.LIPSTICK?_s=RAABAB0', '$198.00', '100% Linen', 100, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('reformation', 'Reformation', 'Jillian Silk Dress', '1318344PZZ', 'https://www.thereformation.com/products/jillian-silk-dress/1318344PZZ.html', 'https://media.thereformation.com/image/upload/f_auto,q_auto,dpr_1.0/w_800,c_scale//PRD-SFCC/1318344/PEAR/1318344.1.PEAR?_s=RAABAB0', '$348.00', '100% Silk', 100, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('reformation', 'Reformation', 'Joliette Dress', '1319017BLK', 'https://www.thereformation.com/products/joliette-dress/1319017BLK.html', 'https://media.thereformation.com/image/upload/f_auto,q_auto,dpr_1.0/w_800,c_scale//PRD-SFCC/1319017/BLACK/1319017.1.BLACK?_s=RAABAB0', '$198.00', '98% Organic Cotton, 2% Spandex', 98, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('reformation', 'Reformation', 'Magnus Dress', '1312571LLN', 'https://www.thereformation.com/products/magnus-dress/1312571LLN.html', 'https://media.thereformation.com/image/upload/f_auto,q_auto,dpr_1.0/w_800,c_scale//PRD-SFCC/1312571/LOUISIANA/1312571.1.LOUISIANA?_s=RAABAB0', '$298.00', '100% Viscose', 100, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('reformation', 'Reformation', 'Manon Denim Midi Dress', '1319334PRR', 'https://www.thereformation.com/products/manon-denim-midi-dress/1319334PRR.html', 'https://media.thereformation.com/image/upload/f_auto,q_auto,dpr_1.0/w_800,c_scale//PRD-SFCC/1319334/PRESPA/1319334.1.PRESPA?_s=RAABAB0', '$218.00', '100% Cotton', 100, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('sandro', 'Sandro', 'Cropped Checked Shirt', 'SFPCM01639_D251', 'https://us.sandro-paris.com/en/p/cropped-checked-shirt/SFPCM01639_D251.html', 'https://us.sandro-paris.com/dw/image/v2/BCMW_PRD/on/demandware.static/-/Sites-master-catalog/default/images/hi-res/Sandro_SFPCM01639-D251_F_1.jpg?sw=800', '$320.00', '100% Cotton', 100, 'tops') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('sandro', 'Sandro', 'Cropped Logo Zip Cotton Shirt', 'SFPCM01635_47', 'https://us.sandro-paris.com/en/p/cropped-logo-zip-cotton-shirt/SFPCM01635_47.html', 'https://us.sandro-paris.com/dw/image/v2/BCMW_PRD/on/demandware.static/-/Sites-master-catalog/default/images/hi-res/Sandro_SFPCM01635-47_F_1.jpg?sw=800', '$365.00', '100% Cotton', 100, 'tops') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('sandro', 'Sandro', 'Cropped Striped Cotton T-shirt', 'SFPTS01692_D222', 'https://us.sandro-paris.com/en/p/cropped-striped-cotton-t-shirt/SFPTS01692_D222.html', 'https://us.sandro-paris.com/dw/image/v2/BCMW_PRD/on/demandware.static/-/Sites-master-catalog/default/images/hi-res/Sandro_SFPTS01692-D222_F_1.jpg?sw=800', '$120.00', '100% Cotton', 100, 'tops') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('sandro', 'Sandro', 'Cropped Striped Shirt', 'SFPCM01599_D251', 'https://us.sandro-paris.com/en/p/cropped-striped-shirt/SFPCM01599_D251.html', 'https://us.sandro-paris.com/dw/image/v2/BCMW_PRD/on/demandware.static/-/Sites-master-catalog/default/images/hi-res/Sandro_SFPCM01599-D251_F_1.jpg?sw=800', '$365.00', '100% Cotton', 100, 'tops') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('sandro', 'Sandro', 'Denim Shirt with Rhinestones', 'SFPCM01571_4785', 'https://us.sandro-paris.com/en/p/denim-shirt-with-rhinestones/SFPCM01571_4785.html', 'https://us.sandro-paris.com/dw/image/v2/BCMW_PRD/on/demandware.static/-/Sites-master-catalog/default/images/hi-res/Sandro_SFPCM01571-4785_F_1.jpg?sw=800', '$365.00', '100% Cotton', 100, 'tops') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('sandro', 'Sandro', 'Embroidered Wool Cashmere Vest', 'SFPPU02762_610', 'https://us.sandro-paris.com/en/p/embroidered-wool-cashmere-vest/SFPPU02762_610.html', 'https://us.sandro-paris.com/dw/image/v2/BCMW_PRD/on/demandware.static/-/Sites-master-catalog/default/images/hi-res/Sandro_SFPPU02762-610_F_1.jpg?sw=800', '$210.00', '68% Wool, 32% Cashmere', 100, 'knitwear') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('sandro', 'Sandro', 'Embroidered and Beaded Shirt', 'SFPCM01668_47', 'https://us.sandro-paris.com/en/p/embroidered-and-beaded-shirt/SFPCM01668_47.html', 'https://us.sandro-paris.com/dw/image/v2/BCMW_PRD/on/demandware.static/-/Sites-master-catalog/default/images/hi-res/Sandro_SFPCM01668-47_F_1.jpg?sw=800', '$400.00', '100% Cotton', 100, 'tops') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('sandro', 'Sandro', 'Floral Jacquard Ruffle Crop Top', 'SFPTO00850_81', 'https://us.sandro-paris.com/en/p/floral-jacquard-ruffle-crop-top/SFPTO00850_81.html', 'https://us.sandro-paris.com/dw/image/v2/BCMW_PRD/on/demandware.static/-/Sites-master-catalog/default/images/hi-res/Sandro_SFPTO00850-81_F_1.jpg?sw=800', '$320.00', '65% Viscose, 35% Linen', 100, 'tops') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('sandro', 'Sandro', 'Floral Print Shirt', 'SFPCM01682_D323', 'https://us.sandro-paris.com/en/p/floral-print-shirt/SFPCM01682_D323.html', 'https://us.sandro-paris.com/dw/image/v2/BCMW_PRD/on/demandware.static/-/Sites-master-catalog/default/images/hi-res/Sandro_SFPCM01682-D323_F_1.jpg?sw=800', '$320.00', '70% Viscose, 30% Linen', 100, 'tops') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('sandro', 'Sandro', 'Floral Print Silk Shirt', 'SFPCM01633_G113', 'https://us.sandro-paris.com/en/p/floral-print-silk-shirt/SFPCM01633_G113.html', 'https://us.sandro-paris.com/dw/image/v2/BCMW_PRD/on/demandware.static/-/Sites-master-catalog/default/images/hi-res/Sandro_SFPCM01633-G113_F_1.jpg?sw=800', '$450.00', '100% Silk', 100, 'tops') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('sandro', 'Sandro', 'Floral Print Silk Shirt (Multi)', 'SFPCM01626_D370', 'https://us.sandro-paris.com/en/p/floral-print-silk-shirt-multi/SFPCM01626_D370.html', 'https://us.sandro-paris.com/dw/image/v2/BCMW_PRD/on/demandware.static/-/Sites-master-catalog/default/images/hi-res/Sandro_SFPCM01626-D370_F_1.jpg?sw=800', '$450.00', '100% Silk', 100, 'tops') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('sandro', 'Sandro', 'Gingham Linen Crop Top', 'SFPTO00896_D251', 'https://us.sandro-paris.com/en/p/gingham-linen-crop-top/SFPTO00896_D251.html', 'https://us.sandro-paris.com/dw/image/v2/BCMW_PRD/on/demandware.static/-/Sites-master-catalog/default/images/hi-res/Sandro_SFPTO00896-D251_F_1.jpg?sw=800', '$300.00', '86% Linen, 14% Polyester', 86, 'tops') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('sandro', 'Sandro', 'Gingham Linen Maxi Dress', 'SFPRO04713_D251', 'https://us.sandro-paris.com/en/p/gingham-linen-maxi-dress/SFPRO04713_D251.html', 'https://us.sandro-paris.com/dw/image/v2/BCMW_PRD/on/demandware.static/-/Sites-master-catalog/default/dw430890b3/images/hi-res/Sandro_SFPRO04713-D251_F_1.jpg?sw=800', '$365.00', '86% linen, 14% polyester', 86, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('sandro', 'Sandro', 'Knit Maxi Dress with Studs', 'SFPRO03983_24', 'https://us.sandro-paris.com/en/p/knit-maxi-dress-with-studs/SFPRO03983_24.html', 'https://us.sandro-paris.com/dw/image/v2/BCMW_PRD/on/demandware.static/-/Sites-master-catalog/default/dw8beb90d3/images/hi-res/Sandro_SFPRO03983-24_F_1.jpg?sw=800', '$340.00', '67% wool, 18% polyamide, 12% polyester, 3% elastane', 67, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('sandro', 'Sandro', 'Maxi Dress with Lace Details', 'SFPRO04828_D221', 'https://us.sandro-paris.com/en/p/maxi-dress-with-lace-details/SFPRO04828_D221.html', 'https://us.sandro-paris.com/dw/image/v2/BCMW_PRD/on/demandware.static/-/Sites-master-catalog/default/dwef988115/images/hi-res/Sandro_SFPRO04828-D221_F_1.jpg?sw=800', '$645.00', '86% linen, 14% polyester', 86, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('sandro', 'Sandro', 'Mini Denim Dress', 'SFPRO04394_D324', 'https://us.sandro-paris.com/en/p/mini-denim-dress/SFPRO04394_D324.html', 'https://us.sandro-paris.com/dw/image/v2/BCMW_PRD/on/demandware.static/-/Sites-master-catalog/default/dw7755d010/images/hi-res/Sandro_SFPRO04394-D324_F_1.jpg?sw=800', '$367.50', '100% cotton', 100, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('sandro', 'Sandro', 'Rhinestone Cropped Denim Shirt', 'SFPCM01562_J002', 'https://us.sandro-paris.com/en/p/rhinestone-cropped-denim-shirt/SFPCM01562_J002.html', 'https://us.sandro-paris.com/dw/image/v2/BCMW_PRD/on/demandware.static/-/Sites-master-catalog/default/images/hi-res/Sandro_SFPCM01562-J002_F_1.jpg?sw=800', '$320.00', '100% Cotton', 100, 'tops') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('sandro', 'Sandro', 'Rhinestone Cropped Shirt', 'SFPCM01432_G023', 'https://us.sandro-paris.com/en/p/rhinestone-cropped-shirt/SFPCM01432_G023.html', 'https://us.sandro-paris.com/dw/image/v2/BCMW_PRD/on/demandware.static/-/Sites-master-catalog/default/images/hi-res/Sandro_SFPCM01432-G023_F_1.jpg?sw=800', '$240.00', '100% Cotton', 100, 'tops') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('sandro', 'Sandro', 'Ruffled Striped Shirt', 'SFPCM01563_D177', 'https://us.sandro-paris.com/en/p/ruffled-striped-shirt/SFPCM01563_D177.html', 'https://us.sandro-paris.com/dw/image/v2/BCMW_PRD/on/demandware.static/-/Sites-master-catalog/default/images/hi-res/Sandro_SFPCM01563-D177_F_1.jpg?sw=800', '$350.00', '100% Cotton', 100, 'tops') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('sandro', 'Sandro', 'Ruffled Top', 'SFPTO00878_E019', 'https://us.sandro-paris.com/en/p/ruffled-top/SFPTO00878_E019.html', 'https://us.sandro-paris.com/dw/image/v2/BCMW_PRD/on/demandware.static/-/Sites-master-catalog/default/images/hi-res/Sandro_SFPTO00878-E019_F_1.jpg?sw=800', '$320.00', '100% Viscose', 100, 'tops') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('sandro', 'Sandro', 'Satin-Effect Maxi Dress', 'SFPRO04783_4111', 'https://us.sandro-paris.com/en/p/satin-effect-maxi-dress/SFPRO04783_4111.html', 'https://us.sandro-paris.com/dw/image/v2/BCMW_PRD/on/demandware.static/-/Sites-master-catalog/default/dwd3c61fa4/images/hi-res/Sandro_SFPRO04783-4111_F_1.jpg?sw=800', '$260.00', '81% lyocell, 19% linen', 100, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('sandro', 'Sandro', 'Scarf Print T-shirt', 'SFPTS01819_D370', 'https://us.sandro-paris.com/en/p/scarf-print-t-shirt/SFPTS01819_D370.html', 'https://us.sandro-paris.com/dw/image/v2/BCMW_PRD/on/demandware.static/-/Sites-master-catalog/default/images/hi-res/Sandro_SFPTS01819-D370_F_1.jpg?sw=800', '$180.00', '100% Cotton', 100, 'tops') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('sandro', 'Sandro', 'Sequin Top', 'SFPTO00898_47', 'https://us.sandro-paris.com/en/p/sequin-top/SFPTO00898_47.html', 'https://us.sandro-paris.com/dw/image/v2/BCMW_PRD/on/demandware.static/-/Sites-master-catalog/default/images/hi-res/Sandro_SFPTO00898-47_F_1.jpg?sw=800', '$350.00', '100% Lyocell', 100, 'tops') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('sandro', 'Sandro', 'Sequined Midi Dress', 'SFPRO04638_47', 'https://us.sandro-paris.com/en/p/sequined-midi-dress/SFPRO04638_47.html', 'https://us.sandro-paris.com/dw/image/v2/BCMW_PRD/on/demandware.static/-/Sites-master-catalog/default/dwfd966630/images/hi-res/Sandro_SFPRO04638-47_F_1.jpg?sw=800', '$560.00', '100% lyocell', 100, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('sandro', 'Sandro', 'Sequinned Striped Vest', 'SFPVE01308_B198', 'https://us.sandro-paris.com/en/p/sequinned-striped-vest/SFPVE01308_B198.html', 'https://us.sandro-paris.com/dw/image/v2/BCMW_PRD/on/demandware.static/-/Sites-master-catalog/default/images/hi-res/Sandro_SFPVE01308-B198_F_1.jpg?sw=800', '$480.00', '97% Viscose, 3% Polyamide', 97, 'tops') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('sandro', 'Sandro', 'Striped V-neck Polo Sweater', 'SFPPU02783_G023', 'https://us.sandro-paris.com/en/p/striped-v-neck-polo-sweater/SFPPU02783_G023.html', 'https://us.sandro-paris.com/dw/image/v2/BCMW_PRD/on/demandware.static/-/Sites-master-catalog/default/images/hi-res/Sandro_SFPPU02783-G023_F_1.jpg?sw=800', '$240.00', '58% Lyocell, 18% Cotton, 18% Polyamide, 6% Silk', 82, 'knitwear') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('the-kooples', 'The Kooples', 'Black Corset Effect Dress', 'FROB32036KBLA09', 'https://www.thekooples.com/eu/en/p/black-corset-effect-dress-FROB32036KBLA09.html', '', '€415.00', '100% Viscose', 100, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('the-kooples', 'The Kooples', 'Long Ruffled Peach Dress', 'FROB32083KNUP01', 'https://www.thekooples.com/eu/en/p/long-ruffled-peach-dress-FROB32083KNUP01.html', '', '€385.00', '100% Viscose', 100, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('the-kooples', 'The Kooples', 'Long Silk Dress with Ecru Lace', 'FROB32057KBEI02', 'https://www.thekooples.com/eu/en/p/long-silk-dress-with-ecru-lace-FROB32057KBEI02.html', '', '€695.00', '100% Silk', 100, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('the-kooples', 'The Kooples', 'Red Floral Print Long Dress with Ruffles', 'FROB32029KRED37', 'https://www.thekooples.com/eu/en/p/red-floral-print-long-dress-with-ruffles-FROB32029KRED37.html', '', '€475.00', '100% Viscose', 100, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('the-kooples', 'The Kooples', 'Red Floral Print Maxi Dress', 'FROB32078KRED37', 'https://www.thekooples.com/eu/en/p/red-floral-print-maxi-dress-FROB32078KRED37.html', '', '€435.00', '100% Viscose', 100, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('the-kooples', 'The Kooples', 'Red Floral Print Short Dress', 'FROB32079KRED37', 'https://www.thekooples.com/eu/en/p/red-floral-print-short-dress-FROB32079KRED37.html', '', '€365.00', '100% Viscose', 100, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('the-kooples', 'The Kooples', 'Short Dress with Black Bow Detail', 'FROB32042KBLA01', 'https://www.thekooples.com/eu/en/p/short-dress-with-black-bow-detail-FROB32042KBLA01.html', '', '€375.00', '100% Viscose', 100, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('the-kooples', 'The Kooples', 'Short Ruffled Peach Dress', 'FROB32003KNUP01', 'https://www.thekooples.com/eu/en/p/short-ruffled-peach-dress-FROB32003KNUP01.html', '', '€350.00', '100% Viscose', 100, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('the-kooples', 'The Kooples', 'White Floral Print Wrap Dress', 'FROB32084KWHI18', 'https://www.thekooples.com/eu/en/p/white-floral-print-wrap-dress-FROB32084KWHI18.html', '', '€415.00', '100% Viscose', 100, 'dresses') ON CONFLICT (product_id) DO NOTHING;
