-- Run this in Supabase SQL Editor to create the products table
CREATE TABLE IF NOT EXISTS products (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  brand_slug TEXT NOT NULL,
  brand_name TEXT NOT NULL,
  name TEXT NOT NULL,
  product_id TEXT NOT NULL UNIQUE,
  url TEXT NOT NULL,
  image_url TEXT,
  price TEXT,
  composition TEXT,
  natural_fiber_percent INTEGER,
  category TEXT NOT NULL DEFAULT 'dresses',
  approved TEXT NOT NULL DEFAULT 'yes',
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Insert products
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('reformation', 'Reformation', 'Ailany Dress', '1319572JGR', 'https://www.thereformation.com/products/ailany-dress/1319572JGR.html', 'https://media.thereformation.com/image/upload/f_auto,q_auto,dpr_1.0/w_800,c_scale//PRD-SFCC/1319572/JADE_GREEN/1319572.1.JADE_GREEN?_s=RAABAB0', '$248.00', '100% Viscose (wood pulp)', 100, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('reformation', 'Reformation', 'Anaiis Silk Dress', '1314547TAV', 'https://www.thereformation.com/products/anaiis-silk-dress/1314547TAV.html', 'https://media.thereformation.com/image/upload/f_auto,q_auto,dpr_1.0/w_800,c_scale//PRD-SFCC/1314547/TARRAGON/1314547.1.TARRAGON?_s=RAABAB0', '$398.00', '100% Silk', 100, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('reformation', 'Reformation', 'Birdie Linen Dress', '1320101OVI', 'https://www.thereformation.com/products/birdie-linen-dress/1320101OVI.html', 'https://media.thereformation.com/image/upload/f_auto,q_auto,dpr_1.0/w_800,c_scale//PRD-SFCC/1320101/LOVIE/1320101.1.LOVIE?_s=RAABAB0', '$298.00', '100% Linen', 100, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('reformation', 'Reformation', 'Cecilia Linen Dress', '1319452DEK', 'https://www.thereformation.com/products/cecilia-linen-dress/1319452DEK.html', 'https://media.thereformation.com/image/upload/f_auto,q_auto,dpr_1.0/w_800,c_scale//PRD-SFCC/1319452/DARK_OATMEAL/1319452.1.DARK_OATMEAL?_s=RAABAB0', '$278.00', '100% Linen', 100, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('reformation', 'Reformation', 'Claribel Dress', '1319500CRM', 'https://www.thereformation.com/products/claribel-dress/1319500CRM.html', 'https://media.thereformation.com/image/upload/f_auto,q_auto,dpr_1.0/w_800,c_scale//PRD-SFCC/1319500/CREAM/1319500.1.CREAM?_s=RAABAB0', '$248.00', '100% Viscose (wood pulp)', 100, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('reformation', 'Reformation', 'Doranni Dress', '1319657JGR', 'https://www.thereformation.com/products/doranni-dress/1319657JGR.html', 'https://media.thereformation.com/image/upload/f_auto,q_auto,dpr_1.0/w_800,c_scale//PRD-SFCC/1319657/JADE_GREEN/1319657.1.JADE_GREEN?_s=RAABAB0', '$298.00', '100% Viscose (wood pulp)', 100, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('reformation', 'Reformation', 'Eden Silk Dress', '1319612PPO', 'https://www.thereformation.com/products/eden-silk-dress/1319612PPO.html', 'https://media.thereformation.com/image/upload/f_auto,q_auto,dpr_1.0/w_800,c_scale//PRD-SFCC/1319612/PLUTO_DOT/1319612.1.PLUTO_DOT?_s=RAABAB0', '$248.00', '100% Silk', 100, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('reformation', 'Reformation', 'Frankie Silk Dress', '1304134RCM', 'https://www.thereformation.com/products/frankie-silk-dress/1304134RCM.html', 'https://media.thereformation.com/image/upload/f_auto,q_auto,dpr_1.0/w_800,c_scale//PRD-SFCC/1304134/MERCY/1304134.1.MERCY?_s=RAABAB0', '$298.00', '100% Silk', 100, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('reformation', 'Reformation', 'Janu Linen Mini Dress', '1319548LPS', 'https://www.thereformation.com/products/janu-linen-mini-dress/1319548LPS.html', 'https://media.thereformation.com/image/upload/f_auto,q_auto,dpr_1.0/w_800,c_scale//PRD-SFCC/1319548/LIPSTICK/1319548.1.LIPSTICK?_s=RAABAB0', '$198.00', '100% Linen', 100, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('reformation', 'Reformation', 'Jillian Silk Dress', '1318344PZZ', 'https://www.thereformation.com/products/jillian-silk-dress/1318344PZZ.html', 'https://media.thereformation.com/image/upload/f_auto,q_auto,dpr_1.0/w_800,c_scale//PRD-SFCC/1318344/PEAR/1318344.1.PEAR?_s=RAABAB0', '$348.00', '100% Silk', 100, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('reformation', 'Reformation', 'Joliette Dress', '1319017BLK', 'https://www.thereformation.com/products/joliette-dress/1319017BLK.html', 'https://media.thereformation.com/image/upload/f_auto,q_auto,dpr_1.0/w_800,c_scale//PRD-SFCC/1319017/BLACK/1319017.1.BLACK?_s=RAABAB0', '$198.00', '98% Organic Cotton, 2% Spandex', 98, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('reformation', 'Reformation', 'Magnus Dress', '1312571LLN', 'https://www.thereformation.com/products/magnus-dress/1312571LLN.html', 'https://media.thereformation.com/image/upload/f_auto,q_auto,dpr_1.0/w_800,c_scale//PRD-SFCC/1312571/LOUISIANA/1312571.1.LOUISIANA?_s=RAABAB0', '$298.00', '100% Viscose', 100, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('reformation', 'Reformation', 'Manon Denim Midi Dress', '1319334PRR', 'https://www.thereformation.com/products/manon-denim-midi-dress/1319334PRR.html', 'https://media.thereformation.com/image/upload/f_auto,q_auto,dpr_1.0/w_800,c_scale//PRD-SFCC/1319334/PRESPA/1319334.1.PRESPA?_s=RAABAB0', '$218.00', '100% Cotton', 100, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('sandro', 'Sandro', 'Gingham Linen Maxi Dress', 'SFPRO04713_D251', 'https://us.sandro-paris.com/en/p/gingham-linen-maxi-dress/SFPRO04713_D251.html', 'https://us.sandro-paris.com/dw/image/v2/BCMW_PRD/on/demandware.static/-/Sites-master-catalog/default/dw430890b3/images/hi-res/Sandro_SFPRO04713-D251_F_1.jpg?sw=800', '$365.00', '86% linen, 14% polyester', 86, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('sandro', 'Sandro', 'Knit Maxi Dress with Studs', 'SFPRO03983_24', 'https://us.sandro-paris.com/en/p/knit-maxi-dress-with-studs/SFPRO03983_24.html', 'https://us.sandro-paris.com/dw/image/v2/BCMW_PRD/on/demandware.static/-/Sites-master-catalog/default/dw8beb90d3/images/hi-res/Sandro_SFPRO03983-24_F_1.jpg?sw=800', '$340.00', '67% wool, 18% polyamide, 12% polyester, 3% elastane', 67, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('sandro', 'Sandro', 'Maxi Dress with Lace Details', 'SFPRO04828_D221', 'https://us.sandro-paris.com/en/p/maxi-dress-with-lace-details/SFPRO04828_D221.html', 'https://us.sandro-paris.com/dw/image/v2/BCMW_PRD/on/demandware.static/-/Sites-master-catalog/default/dwef988115/images/hi-res/Sandro_SFPRO04828-D221_F_1.jpg?sw=800', '$645.00', '86% linen, 14% polyester', 86, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('sandro', 'Sandro', 'Mini Denim Dress', 'SFPRO04394_D324', 'https://us.sandro-paris.com/en/p/mini-denim-dress/SFPRO04394_D324.html', 'https://us.sandro-paris.com/dw/image/v2/BCMW_PRD/on/demandware.static/-/Sites-master-catalog/default/dw7755d010/images/hi-res/Sandro_SFPRO04394-D324_F_1.jpg?sw=800', '$367.50', '100% cotton', 100, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('sandro', 'Sandro', 'Satin-Effect Maxi Dress', 'SFPRO04783_4111', 'https://us.sandro-paris.com/en/p/satin-effect-maxi-dress/SFPRO04783_4111.html', 'https://us.sandro-paris.com/dw/image/v2/BCMW_PRD/on/demandware.static/-/Sites-master-catalog/default/dwd3c61fa4/images/hi-res/Sandro_SFPRO04783-4111_F_1.jpg?sw=800', '$260.00', '81% lyocell, 19% linen', 100, 'dresses') ON CONFLICT (product_id) DO NOTHING;
INSERT INTO products (brand_slug, brand_name, name, product_id, url, image_url, price, composition, natural_fiber_percent, category) VALUES ('sandro', 'Sandro', 'Sequined Midi Dress', 'SFPRO04638_47', 'https://us.sandro-paris.com/en/p/sequined-midi-dress/SFPRO04638_47.html', 'https://us.sandro-paris.com/dw/image/v2/BCMW_PRD/on/demandware.static/-/Sites-master-catalog/default/dwfd966630/images/hi-res/Sandro_SFPRO04638-47_F_1.jpg?sw=800', '$560.00', '100% lyocell', 100, 'dresses') ON CONFLICT (product_id) DO NOTHING;

