const LOCAL_BRAND_IMAGES: Record<string, string> = {
  "acne-studios": "/brands/acne-studios.jpg",
  "agolde": "/brands/agolde.jpg",
  "aje": "/brands/aje.jpg",
  "a-l-c-": "/brands/a-l-c-.jpg",
  "allsaints": "/brands/allsaints.jpg",
  "ami-paris": "/brands/ami-paris.jpg",
  "anine-bing": "/brands/anine-bing.jpg",
  "bash": "/brands/bash.jpg",
  "bottega-veneta": "/brands/bottega-veneta.jpg",
  "camilla-and-marc": "/brands/camilla-and-marc.jpg",
  "chloe": "/brands/chloe.jpg",
  "citizens-of-humanity": "/brands/citizens-of-humanity.jpg",
  "club-monaco": "/brands/club-monaco.jpg",
  "cult-gaia": "/brands/cult-gaia.jpg",
  "diesel": "/brands/diesel.jpg",
  "dissh": "/brands/dissh.jpg",
  "dl1961": "/brands/dl1961.jpg",
  "equipment": "/brands/equipment.jpg",
  "esse-studios": "/brands/esse-studios.jpg",
  "faithfull-the-brand": "/brands/faithfull-the-brand.jpg",
  "fleur-du-mal": "/brands/fleur-du-mal.jpg",
  "frame": "/brands/frame.jpg",
  "ganni": "/brands/ganni.jpg",
  "iro": "/brands/iro.jpg",
  "isabel-marant":
    "https://intl.isabelmarant.com/cdn/shop/files/Isabel_Marant_FW25_look_01.jpg?v=1741306390&width=1920",
  "joseph": "/brands/joseph.jpg",
  "khaite": "/brands/khaite.jpg",
  "loewe": "/brands/loewe.jpg",
  "maje": "/brands/maje.jpg",
  "mara-hoffman": "/brands/mara-hoffman.jpg",
  "margaret-howell": "/brands/margaret-howell.jpg",
  "maria-mcmanus": "/brands/maria-mcmanus.jpg",
  "mother": "/brands/mother.jpg",
  "nanushka": "/brands/nanushka.jpg",
  "nili-lotan": "/brands/nili-lotan.jpg",
  "proenza-schouler": "/brands/proenza-schouler.jpg",
  "rachel-comey": "/brands/rachel-comey.jpg",
  "l-agence":
    "https://lagence.com/cdn/shop/files/Hero-Desktop_2_7ff67339-b858-4593-99ee-6be2b035a36b.jpg?v=1752629879&width=1920",
  "rag-bone": "/brands/rag-bone.jpg",
  "rag-and-bone": "/brands/rag-bone.jpg",
  "rails": "/brands/rails.jpg",
  "re-done": "/brands/re-done.png",
  "reformation": "/brands/reformation.jpg",
  "reiss": "/brands/reiss.jpg",
  "rixo": "/brands/rixo.jpg",
  "rodebjer": "/brands/rodebjer.jpg",
  "sandro": "/brands/sandro.jpg",
  "sea-new-york": "/brands/sea-new-york.jpg",
  "sezane": "/brands/sezane.jpg",
  "st-agni": "/brands/st-agni.jpg",
  "stella-mccartney": "/brands/stella-mccartney.jpg",
  "stine-goya": "/brands/stine-goya.jpg",
  "ted-baker": "/brands/ted-baker.jpg",
  "theory": "/brands/theory.jpg",
  "staud":
    "https://staud.clothing/cdn/shop/files/Nav_Summer_Tommys.jpg?v=1777958857&width=1920",
  "the-row": "/brands/the-row.jpg",
  "tibi": "/brands/tibi.jpg",
  "toteme": "/brands/toteme.jpg",
  "ulla-johnson": "/brands/ulla-johnson.jpg",
  "veda": "/brands/veda.jpg",
  "velvet": "/brands/velvet.jpg",
  "veronica-beard": "/brands/veronica-beard.jpg",
  "vince": "/brands/vince.webp",
  "zadig-voltaire": "/brands/zadig-voltaire.jpg",
  "zimmermann": "/brands/zimmermann.jpg",
  "7-for-all-mankind": "/brands/7-for-all-mankind.jpg",
  "splendid": "/brands/splendid.jpg",
};

const NAME_TO_SLUG: Record<string, string> = {
  "a.l.c.": "a-l-c-",
  "alc": "a-l-c-",
  "a-l-c-": "a-l-c-",
  "acne studios": "acne-studios",
  "agolde": "agolde",
  "aje": "aje",
  "allsaints": "allsaints",
  "all saints": "allsaints",
  "ami paris": "ami-paris",
  "anine bing": "anine-bing",
  "ba&sh": "bash",
  "bash": "bash",
  "bottega veneta": "bottega-veneta",
  "camilla and marc": "camilla-and-marc",
  "chloé": "chloe",
  "chloe": "chloe",
  "citizens of humanity": "citizens-of-humanity",
  "club monaco": "club-monaco",
  "cult gaia": "cult-gaia",
  "diesel": "diesel",
  "dissh": "dissh",
  "dl1961": "dl1961",
  "equipment": "equipment",
  "esse studios": "esse-studios",
  "faithfull the brand": "faithfull-the-brand",
  "fleur du mal": "fleur-du-mal",
  "frame": "frame",
  "ganni": "ganni",
  "iro": "iro",
  "isabel marant": "isabel-marant",
  "joseph": "joseph",
  "khaite": "khaite",
  "l'agence": "l-agence",
  "lagence": "l-agence",
  "loewe": "loewe",
  "maje": "maje",
  "mara hoffman": "mara-hoffman",
  "margaret howell": "margaret-howell",
  "maria mcmanus": "maria-mcmanus",
  "mother denim": "mother",
  "mother": "mother",
  "nanushka": "nanushka",
  "nili lotan": "nili-lotan",
  "proenza schouler": "proenza-schouler",
  "rachel comey": "rachel-comey",
  "rag & bone": "rag-and-bone",
  "rag bone": "rag-and-bone",
  "rag-bone": "rag-and-bone",
  "rails": "rails",
  "re/done": "re-done",
  "re-done": "re-done",
  "reformation": "reformation",
  "reiss": "reiss",
  "rixo": "rixo",
  "rodebjer": "rodebjer",
  "sandro": "sandro",
  "sea new york": "sea-new-york",
  "sézane": "sezane",
  "sezane": "sezane",
  "st. agni": "st-agni",
  "st agni": "st-agni",
  "stella mccartney": "stella-mccartney",
  "stine goya": "stine-goya",
  "ted baker": "ted-baker",
  "the kooples": "the-kooples",
  "the row": "the-row",
  "theory": "theory",
  "staud": "staud",
  "tibi": "tibi",
  "totême": "toteme",
  "toteme": "toteme",
  "ulla johnson": "ulla-johnson",
  "veda": "veda",
  "velvet by graham & spencer": "velvet",
  "velvet": "velvet",
  "veronica beard": "veronica-beard",
  "vince": "vince",
  "zadig & voltaire": "zadig-voltaire",
  "zadig voltaire": "zadig-voltaire",
  "zimmermann": "zimmermann",
  "7 for all mankind": "7-for-all-mankind",
  "7forallmankind": "7-for-all-mankind",
  "splendid": "splendid",
};

export function getBrandHeroImage(brandName: string): string | null {
  const lower = brandName.toLowerCase().trim();
  const slug = NAME_TO_SLUG[lower] || lower;
  return LOCAL_BRAND_IMAGES[slug] || null;
}
