export const CURATED_QUALITY_SCORES: Record<string, number> = {
  "the row": 96,
  "brunello cucinelli": 97,
  "loro piana": 98,
  "margaret howell": 95,
  "lemaire": 93,
  "jil sander": 91,
  "totême": 92,
  "toteme": 92,
  "eileen fisher": 90,
  "joseph": 90,

  "khaite": 88,
  "loewe": 85,
  "bottega veneta": 82,
  "chloé": 83,
  "chloe": 83,
  "stella mccartney": 80,
  "acne studios": 78,
  "isabel marant": 76,
  "nanushka": 75,
  "proenza schouler": 77,
  "frame": 74,
  "equipment": 82,
  "citizens of humanity": 78,
  "agolde": 76,
  "rag & bone": 72,
  "re/done": 73,
  "vince": 80,
  "ami paris": 75,
  "a.p.c.": 79,
  "nili lotan": 82,
  "filippa k": 78,

  "sézane": 68,
  "sezane": 68,
  "ba&sh": 62,
  "ganni": 65,
  "anine bing": 64,
  "reformation": 66,
  "sandro": 58,
  "maje": 55,
  "reiss": 60,
  "theory": 65,
  "club monaco": 58,
  "iro": 56,
  "zadig & voltaire": 54,
  "arket": 68,
  "& other stories": 60,
  "claudie pierlot": 52,

  "the kooples": 60,
  "allsaints": 48,
  "all saints": 48,
  "ted baker": 42,
  "cos": 55,
  "max mara": 70,
  "zimmermann": 62,
  "jacquemus": 72,

  "everlane": 70,
  "quince": 80,
  "massimo dutti": 65,
  "l'agence": 62,
  "lagence": 62,

  "loulou studio": 78,
  "st. agni": 76,
  "maria mcmanus": 82,

  "ulla johnson": 74,
  "veronica beard": 68,
  "cult gaia": 65,
  "rachel comey": 78,
  "sea new york": 72,
  "rixo": 66,
  "faithfull the brand": 70,
  "stine goya": 65,
  "tibi": 76,
  "mara hoffman": 80,
  "aje": 68,
  "sir the label": 74,
  "camilla and marc": 72,
  "esse studios": 78,
  "dissh": 55,
  "rodebjer": 75,
  "velvet by graham & spencer": 65,
  "rails": 58,
  "derek lam 10 crosby": 72,
  "derek lam": 72,
  "rebecca taylor": 64,
  "tanya taylor": 68,
  "fleur du mal": 72,
  "a.l.c.": 66,
  "mother denim": 62,
  "mother": 62,
  "dl1961": 60,
  "rebecca minkoff": 55,
  "525 america": 58,
  "34 heritage": 62,
  "veda": 70,
  "diesel": 80,
};

export function getCuratedScore(brandName: string): number | null {
  const lower = (brandName || "").toLowerCase().trim();
  return CURATED_QUALITY_SCORES[lower] ?? null;
}
