-- Run this AFTER the generic update to fix known brand domains
UPDATE designers SET website = 'https://alexanderwang.com' WHERE lower(trim(name)) = 'alexander wang';
UPDATE designers SET website = 'https://ralphlauren.com' WHERE lower(trim(name)) = 'ralph lauren';
UPDATE designers SET website = 'https://tommyhilfiger.com' WHERE lower(trim(name)) = 'tommy hilfiger';
UPDATE designers SET website = 'https://calvinklein.com' WHERE lower(trim(name)) = 'calvin klein';
UPDATE designers SET website = 'https://michaelkors.com' WHERE lower(trim(name)) = 'michael kors';
UPDATE designers SET website = 'https://marcjacobs.com' WHERE lower(trim(name)) = 'marc jacobs';
UPDATE designers SET website = 'https://katespade.com' WHERE lower(trim(name)) = 'kate spade';
UPDATE designers SET website = 'https://toryburch.com' WHERE lower(trim(name)) = 'tory burch';
UPDATE designers SET website = 'https://dvf.com' WHERE lower(trim(name)) = 'diane von furstenberg';
UPDATE designers SET website = 'https://oscardelarenta.com' WHERE lower(trim(name)) = 'oscar de la renta';
UPDATE designers SET website = 'https://carolinaherrera.com' WHERE lower(trim(name)) = 'carolina herrera';
UPDATE designers SET website = 'https://helmutlang.com' WHERE lower(trim(name)) = 'helmut lang';
UPDATE designers SET website = 'https://rag-bone.com' WHERE lower(trim(name)) = 'rag & bone';
UPDATE designers SET website = 'https://acnestudios.com' WHERE lower(trim(name)) = 'acne studios';
UPDATE designers SET website = 'https://apc.fr' WHERE lower(trim(name)) = 'a.p.c.';
UPDATE designers SET website = 'https://maisonmargiela.com' WHERE lower(trim(name)) = 'maison margiela';
UPDATE designers SET website = 'https://rickowens.eu' WHERE lower(trim(name)) = 'rick owens';
UPDATE designers SET website = 'https://therow.com' WHERE lower(trim(name)) = 'the row';
UPDATE designers SET website = 'https://bottegaveneta.com' WHERE lower(trim(name)) = 'bottega veneta';
UPDATE designers SET website = 'https://ysl.com' WHERE lower(trim(name)) = 'saint laurent';
UPDATE designers SET website = 'https://louisvuitton.com' WHERE lower(trim(name)) = 'louis vuitton';
UPDATE designers SET website = 'https://dolcegabbana.com' WHERE lower(trim(name)) = 'dolce & gabbana';
UPDATE designers SET website = 'https://armani.com' WHERE lower(trim(name)) IN ('armani', 'giorgio armani', 'emporio armani');
UPDATE designers SET website = 'https://off---white.com' WHERE lower(trim(name)) IN ('off-white', 'off white');
UPDATE designers SET website = 'https://fearofgod.com' WHERE lower(trim(name)) = 'fear of god';
UPDATE designers SET website = 'https://tomford.com' WHERE lower(trim(name)) = 'tom ford';
UPDATE designers SET website = 'https://stellamccartney.com' WHERE lower(trim(name)) = 'stella mccartney';
UPDATE designers SET website = 'https://isabelmarant.com' WHERE lower(trim(name)) = 'isabel marant';
UPDATE designers SET website = 'https://stories.com' WHERE lower(trim(name)) = '& other stories';
UPDATE designers SET website = 'https://massimodutti.com' WHERE lower(trim(name)) = 'massimo dutti';
UPDATE designers SET website = 'https://jcrew.com' WHERE lower(trim(name)) = 'j.crew';
UPDATE designers SET website = 'https://frame-store.com' WHERE lower(trim(name)) = 'frame';
UPDATE designers SET website = 'https://brunellocucinelli.com' WHERE lower(trim(name)) = 'brunello cucinelli';
UPDATE designers SET website = 'https://loropiana.com' WHERE lower(trim(name)) = 'loro piana';
UPDATE designers SET website = 'https://tods.com' WHERE lower(trim(name)) = 'tod''s';
UPDATE designers SET website = 'https://ferragamo.com' WHERE lower(trim(name)) = 'salvatore ferragamo';
UPDATE designers SET website = 'https://jimmychoo.com' WHERE lower(trim(name)) = 'jimmy choo';
UPDATE designers SET website = 'https://christianlouboutin.com' WHERE lower(trim(name)) = 'christian louboutin';
UPDATE designers SET website = 'https://newbalance.com' WHERE lower(trim(name)) = 'new balance';
UPDATE designers SET website = 'https://thenorthface.com' WHERE lower(trim(name)) = 'the north face';
UPDATE designers SET website = 'https://canadagoose.com' WHERE lower(trim(name)) = 'canada goose';
UPDATE designers SET website = 'https://paulsmith.com' WHERE lower(trim(name)) = 'paul smith';
UPDATE designers SET website = 'https://viviennewestwood.com' WHERE lower(trim(name)) = 'vivienne westwood';
UPDATE designers SET website = 'https://alexandermcqueen.com' WHERE lower(trim(name)) = 'alexander mcqueen';
UPDATE designers SET website = 'https://maxmara.com' WHERE lower(trim(name)) = 'max mara';
UPDATE designers SET website = 'https://jilsander.com' WHERE lower(trim(name)) = 'jil sander';
UPDATE designers SET website = 'https://sacai.jp' WHERE lower(trim(name)) = 'sacai';
UPDATE designers SET website = 'https://isseymiyake.com' WHERE lower(trim(name)) = 'issey miyake';
UPDATE designers SET website = 'https://amiparis.com' WHERE lower(trim(name)) = 'ami paris';
UPDATE designers SET website = 'https://ourlegacy.com' WHERE lower(trim(name)) = 'our legacy';
UPDATE designers SET website = 'https://carhartt-wip.com' WHERE lower(trim(name)) = 'carhartt wip';
UPDATE designers SET website = 'https://thereformation.com' WHERE lower(trim(name)) = 'reformation';
UPDATE designers SET website = 'https://aninebing.com' WHERE lower(trim(name)) = 'anine bing';
UPDATE designers SET website = 'https://proenzaschouler.com' WHERE lower(trim(name)) = 'proenza schouler';
UPDATE designers SET website = 'https://hugoboss.com' WHERE lower(trim(name)) IN ('hugo boss', 'boss');
UPDATE designers SET website = 'https://mcmworldwide.com' WHERE lower(trim(name)) = 'mcm';
UPDATE designers SET website = 'https://chloe.com' WHERE lower(trim(name)) IN ('chloé', 'chloe');
UPDATE designers SET website = 'https://sandro-paris.com' WHERE lower(trim(name)) = 'sandro';
UPDATE designers SET website = 'https://zadig-et-voltaire.com' WHERE lower(trim(name)) = 'zadig & voltaire';
UPDATE designers SET website = 'https://ba-sh.com' WHERE lower(trim(name)) = 'ba&sh';
UPDATE designers SET website = 'https://hm.com' WHERE lower(trim(name)) = 'h&m';
UPDATE designers SET website = 'https://a-cold-wall.com' WHERE lower(trim(name)) = 'a_cold_wall*';
UPDATE designers SET website = 'https://msgm.it' WHERE lower(trim(name)) = 'msgm';
UPDATE designers SET website = 'https://31philliplim.com' WHERE lower(trim(name)) = '3.1 phillip lim';
UPDATE designers SET website = 'https://thombrowne.com' WHERE lower(trim(name)) = 'thom browne';
UPDATE designers SET website = 'https://bape.com' WHERE lower(trim(name)) = 'a bathing ape';
UPDATE designers SET website = 'https://supremenewyork.com' WHERE lower(trim(name)) = 'supreme';
UPDATE designers SET website = 'https://goldengoose.com' WHERE lower(trim(name)) = 'golden goose';
UPDATE designers SET website = 'https://commonprojects.com' WHERE lower(trim(name)) = 'common projects';
UPDATE designers SET website = 'https://freepeople.com' WHERE lower(trim(name)) = 'free people';
UPDATE designers SET website = 'https://brooksbrothers.com' WHERE lower(trim(name)) = 'brooks brothers';
UPDATE designers SET website = 'https://aloyoga.com' WHERE lower(trim(name)) = 'alo yoga';
UPDATE designers SET website = 'https://eileenfisher.com' WHERE lower(trim(name)) = 'eileen fisher';
UPDATE designers SET website = 'https://citizensofhumanity.com' WHERE lower(trim(name)) = 'citizens of humanity';
UPDATE designers SET website = 'https://motherdenim.com' WHERE lower(trim(name)) = 'mother';
UPDATE designers SET website = 'https://7forallmankind.com' WHERE lower(trim(name)) = '7 for all mankind';
UPDATE designers SET website = 'https://veja-store.com' WHERE lower(trim(name)) = 'veja';
UPDATE designers SET website = 'https://on-running.com' WHERE lower(trim(name)) = 'on running';
UPDATE designers SET website = 'https://hermes.com' WHERE lower(trim(name)) IN ('hermès', 'hermes');

-- Verify the results
SELECT COUNT(*) AS total_with_website FROM designers WHERE website IS NOT NULL;
SELECT COUNT(*) AS total_without_website FROM designers WHERE website IS NULL;
SELECT name, website FROM designers WHERE name IN ('Gucci', 'Prada', 'Louis Vuitton', 'Chanel', 'Dior', 'Balenciaga', 'Hermès', 'Saint Laurent', 'The Row', 'A.P.C.') ORDER BY name;
