-- Prefer products.garment_type over stale MV rows (fixes Pajama Shirt → shirts drift without full MV refresh).

CREATE OR REPLACE VIEW public.live_products_apparel AS
 SELECT m.id,
    m.brand_slug,
    m.brand_name,
    m.name,
    m.product_id,
    m.url,
    m.image_url,
    m.price,
    m.composition,
    m.natural_fiber_percent,
    m.category,
    m.approved,
    m.created_at,
    m.matching_set_id,
    m.is_sale,
    m.original_price,
    m.barcode,
    m.upc,
    m.ean,
    m.sku,
    m.qr_code,
    m.retailer,
    m.material_summary,
    m.intertexe_quality_status,
    m.scan_count,
    m.last_scanned_at,
    m.tags,
    m.collection_slugs,
    m.editorial_categories,
    m.material_metadata,
    m.added_at,
    m.updated_at,
    m.currency,
    m.retailer_country,
    m.raw_price,
    m.retailer_mid,
    m.feed_source,
    m.feed_url,
    m.last_seen_at,
    m.is_active,
    m.region,
    m.display_excluded_reason,
    m.catalog_scope,
    m.canonical_id,
    m.gender_scope,
    m.fiber_primary,
    m.fiber_subtype,
    m.fiber_subtype_label,
    m.color,
    m.last_price_check,
    m.stock_status,
    m.country_of_origin,
    m.care_instructions,
    m.has_recycled_content,
    m.recycled_content_percent,
    m.fiber_breakdown,
    m.dpp_ready,
    m.dpp_record_url,
    m.sustainability_certifications,
    m.manufacturer_name,
    m.manufacturer_country,
    m.material_source,
    m.end_of_life_instructions,
    m.color_normalized,
    m.retailer_name,
    m.discount_percent,
    m.size_options,
    m.product_url_us,
    m.product_url_uk,
    m.price_changed_at,
    m.is_displayable,
    coalesce(p.garment_type, m.garment_type) AS garment_type,
    p.is_editor_pick,
    p.editor_picked_at
   FROM live_products_apparel_mat m
     LEFT JOIN products p ON p.id = m.id;

GRANT SELECT ON public.live_products_apparel TO anon, authenticated, service_role;
NOTIFY pgrst, 'reload schema';
